services:
  backendapi:
    build: .
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: db
      MONGO_USER: plim1025
      MONGO_PASSWORD: HztCYK5vmdax7s8J
      MONGO_DB_NAME: Tarpaulin
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - 6379:6379 