services:
  db:
    image: mongo

  redis:
    image: redis
    ports:
      - 6379:6379

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: db
      MONGO_USER: plim1025
      MONGO_PASSWORD: HztCYK5vmdax7s8J
      MONGO_DB_NAME: Assignment4
    depends_on:
      - db
      - redis
    restart: on-failure